{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Erros e exce√ß√µes\n",
    "\n",
    "## Objetivos\n",
    "\n",
    "- Compreender as diferentes mensagens de erros em Python;\n",
    "- Ser capaz de identificar erros l√≥gicos e sint√°ticos a partir de mensagens de erro;\n",
    "- Inferir poss√≠veis exce√ß√µes que podem ser lan√ßadas pelo c√≥digo;\n",
    "- Implementar tratamento de exce√ß√µes;\n",
    "\n",
    "---\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Introdu√ß√£o\n",
    "\n",
    "- A primeira coisa que aprendemos em programa√ß√£o √© implementar um programa simples que imprime (com a fun√ß√£o ``print``) uma mensagem qualquer, tradicionalmente \"Hello World\" ou \"Ol√° Mundo\".\n",
    "- A segunda coisa que aprendemos √© como o interpretador do Python indica a presen√ßa de (muitos) erros no c√≥digo üòù"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Erros l√≥gicos\n",
    "\n",
    "- Podem ser entendidos como uma __m√° defini√ß√£o das instru√ß√µes__ no c√≥digo pelo programador que __n√£o resulta na sa√≠da esperada__, dada uma __entrada correta__. \n",
    "- Dependem principalmente do __entendimento do dom√≠nio do problema__ e das __habilidades do programador__.\n",
    "- Exemplos de erros l√≥gicos:\n",
    "    - Usar nome incorreto de vari√°vel ou fun√ß√£o;\n",
    "    - Utilizar a quantidade equivocada de espa√ßamento para definir blocos de c√≥digo;\n",
    "    - Criar uma condi√ß√£o com express√µes booleanas que produzem o resultado l√≥gico incorreto;\n",
    "    - Usar divis√£o inteira para n√∫meros com ponto flutuante;\n",
    "    - Entre outros."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Erros sint√°ticos\n",
    "\n",
    "- Acontecem quando o compilador ou interpretador n√£o reconhece as instru√ß√µes do c√≥digo ou terminal inseridas pelo programador; \n",
    "- Nem sempre √© trivial encontrar tal erro;\n",
    "- Geralmente resulta na imediata interrup√ß√£o da execu√ß√£o do programa.\n",
    "- Exemplo:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-1-3257c076f0e2>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-1-3257c076f0e2>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    while True print(\"Ol√°, Mundo!\")\u001b[0m\n\u001b[1;37m               ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "while True print(\"Ol√°, Mundo!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- Aprendemos que a estrutura de decis√£o ``while`` requer uma condi√ß√£o seguida de dois pontos ``:``. Logo em seguida, adicionamos um n√≠vel de indenta√ß√£o marcando o in√≠cio do bloco de instru√ß√µes.\n",
    "- No terminal onde o c√≥digo √© executado, s√£o indicados o arquivo, linha e um s√≠mbolo de ``^`` indicando a posi√ß√£o na instru√ß√£o.\n",
    "- A √∫ltima linha indica o tipo de erro, neste caso um erro de sintaxe.\n",
    "- Abaixo exemplificamos alguns tipos de erro:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### SyntaxError\n",
    "\n",
    "- O parser encontra um erro de sintaxe.\n",
    "- Erro de sintaxe √© um erro onde alguma instru√ß√£o no c√≥digo de uma linguagem de programa√ß√£o espec√≠fica n√£o segue as regras definidas pela linguagem."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = \"100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for e in [1, 2, 3, 4]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "msg = \"Uma mensagem qualquer.\"\n",
    "\n",
    "print msg"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### IndentationError\n",
    "\n",
    "- Quando a indenta√ß√£o n√£o √© realizada corretamente dos blocos de c√≥digos n√£o √© realizada corretamente."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "contador = 1\n",
    "\n",
    "while contador < 100:\n",
    "contador = contador + 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### KeyError e IndexError\n",
    "\n",
    "- IndexError e KeyError ocorre quando tentamos acessar um elemento de uma lista ou dicion√°rio utilizando valores de √≠ndices ou chaves inexistentes, respectivamente."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "L = list(range(10))\n",
    "L[11]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "x1 = list(range(10))\n",
    "x2 = list(range(10,20))\n",
    "\n",
    "dicionario = dict(zip(x1,x2))\n",
    "\n",
    "print(dicionario)\n",
    "\n",
    "print(dicionario[55])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### NameError\n",
    "\n",
    "- Ocorre quando o interpretador se deparar com um nome de vari√°vel local ou global n√£o definida."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'x' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-da7782712f5d>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mif\u001b[0m \u001b[0mx\u001b[0m \u001b[1;33m>\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx\u001b[0m\u001b[1;33m+\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'x' is not defined"
     ]
    }
   ],
   "source": [
    "if x > 0:\n",
    "    print(x+1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ValueError\n",
    "\n",
    "- Ocorre quando uma opera√ß√£o ou fun√ß√£o recebe uma valor n√£o-apropriado; "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "float(\"A\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "mensagem = \"Esta √© apenas uma simples mensagem.\"\n",
    "\n",
    "print(\"√çndice = \",mensagem.index(\"apenas\"))\n",
    "\n",
    "print(\"__\"*30)\n",
    "\n",
    "print(mensagem.index(\"complexa\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### TypeError\n",
    "\n",
    "- Quando uma opera√ß√£o ou fun√ß√£o recebe uma tipo n√£o apropriado; \n",
    "- Utiliza√ß√£o de v√≠rgula em vez de ponto decimal para representar n√∫meros com ponto flutuante;\n",
    "    - Fun√ß√£o v√™ a chamada como usando mais argumentos do que ela requer;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(int(12.2))\n",
    "\n",
    "print(int(12,2))\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- Mais exemplos de erros da linguagem de programa√ß√£o Python podem ser encontrados na documenta√ß√£o do Python (https://docs.python.org/3/tutorial/errors.html)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "***\n",
    "\n",
    "## Exce√ß√µes\n",
    "- Ocorrem em tempo de execu√ß√£o; \n",
    "- Mesmo quando a sintaxe do seu c√≥digo est√° correta, mas o programa se depara com uma situa√ß√£o que n√£o permite que realize a instru√ß√£o. \n",
    "- Podem ser manipuladas de forma que n√£o sejam \"fatais\" para o programa.\n",
    "- Tipos de exce√ß√µes e descri√ß√£o pode ser encontrada em: \n",
    "    - https://docs.python.org/2.7/library/exceptions.html\n",
    "    - https://docs.python.org/3.4/library/exceptions.html\n",
    "- Diferenciamos erros de exce√ß√µes pelo fato dos erros acontecerem durante a etapa de compila√ß√£o do seu programa (convers√£o para byte-code) enquanto que exce√ß√µes acontecem durante a execu√ß√£o."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tratamento de exce√ß√µes\n",
    "\n",
    "- Python utiliza blocos especializados para tratamento de exce√ß√µes: try, except e finally; \n",
    "- ``try``: delimita um bloco de c√≥digos que queremos executar e testa para determinado(s) tipo(s) de erro(s);\n",
    "- ``except``: permite manipular o erro quando for testado positivo para sua ocorr√™ncia no bloco ``try``;\n",
    "- ``finally`` (opcional): permite execu√ß√£o de c√≥digo independente do resultado de ``try``/``except``."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Exemplo:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    print(v)\n",
    "except NameError:\n",
    "    print(\"A vari√°vel v n√£o foi definida em lugar nenhum!\")\n",
    "finally:\n",
    "    print(\"Vou executar independentemente\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "üí£ Experimente executar somente ``print(v)`` sem tratamento de exce√ß√£o."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Funcionamento de ``try``/``except``/``finally``\n",
    "\n",
    "<ol>\n",
    "    <li>O bloco delimitado por try √© executado.</li>\n",
    "    <li>Caso n√£o ocorra nenhuma exce√ß√£o, o bloco except √© ignorado e a execu√ß√£o do bloco delimitado por try termina. </li>\n",
    "    <li>Caso ocorra uma exce√ß√£o durante a execu√ß√£o do bloco delimitado por try, a execu√ß√£o do restante do bloco √© interrompida.</li>\n",
    "    <li>Se o tipo da exce√ß√£o for a mesma definida pelo bloco except (por exemplo, ArithmeticError, IndentationError, SyntaxError, etc), o bloco delimitado por except √© executado, permitindo a continuidade da execu√ß√£o do programa.</li>\n",
    "    <li>Se o tipo da exce√ß√£o n√£o for definido em nenhum bloco except subsequente ao try, significa que a exce√ß√£o n√£o √© manipulada, a execu√ß√£o √© interrompida e emite-se uma mensagem de erro.</li>\n",
    "    <li>O bloco finally sempre √© executado.</li>\n",
    "</ol>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exemplos:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Varios tratamentos\n",
    "\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    arquivo = open(\"numeros.docx\")\n",
    "    ### outras instru√ß√µes\n",
    "    \n",
    "except IOError as erro_entrada_saida:\n",
    "    errno,strerror = erro_entrada_saida.args\n",
    "    print(\"Erro de entrada de sa√≠da ({0}): {1}\".format(errno,strerror))\n",
    "\n",
    "except ValueError:\n",
    "    print(\"N√∫mero no arquivo inv√°lido.\")\n",
    "    \n",
    "except:\n",
    "    print(\"Erro inesperado:\", sys.exc_info()[0])\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- ``args`` √© uma tupla que armazena os argumentos de um construtor de exce√ß√µes;\n",
    "- O primeiro elemento da tupla (``errno``) √© o c√≥digo de erro;\n",
    "- O segundo elemento da tupla (``strerror``) √© a mensagem de erro;\n",
    "- Ambos elementos s√£o emitidos pelo sistema operacional e seguem o padr√£o da linguagem C.\n",
    "- O √∫ltimo bloco ``except`` √© um tratamento gen√©tico. __Experimente remover o bloco do ``IOError`` e executar o c√≥digo acima novamente__."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Fun√ß√£o sem tratamento de exce√ß√£o interno"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "N√£o foi passado um valor num√©rico para a fun√ß√£o:  invalid literal for int() with base 10: '10.5'\n",
      "Continua execu√ß√£o.\n"
     ]
    }
   ],
   "source": [
    "def float_to_int(num):\n",
    "    return int(num)\n",
    "\n",
    "try:\n",
    "    print(float_to_int(\"10.5\"))\n",
    "except ValueError as erro:\n",
    "    print(\"N√£o foi passado um valor num√©rico para a fun√ß√£o: \", erro)\n",
    "\n",
    "print(\"Continua execu√ß√£o.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Fun√ß√£o com tratamento de exce√ß√£o interno"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "N√£o foi passado um valor num√©rico para a fun√ß√£o:  invalid literal for int() with base 10: '12.3'\n",
      "Erro durante a execu√ß√£o da fun√ß√£o float_to_int_2!\n",
      "Continua a execu√ß√£o.\n"
     ]
    }
   ],
   "source": [
    "def float_to_int_2(num):\n",
    "    try:\n",
    "        return int(num)\n",
    "    except ValueError as erro:\n",
    "        print(\"N√£o foi passado um valor num√©rico para a fun√ß√£o: \", erro)\n",
    "    return -1\n",
    "\n",
    "result = float_to_int_2(\"12.3\")\n",
    "\n",
    "if result == -1:\n",
    "    print(\"Erro durante a execu√ß√£o da fun√ß√£o float_to_int_2!\")\n",
    "    \n",
    "print(\"Continua a execu√ß√£o.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ``raise``\n",
    "\n",
    "- Em Python, as exce√ß√µes s√£o lan√ßadas quando ocorrem erros em tempo de execu√ß√£o.\n",
    "- A palavra-chave ``raise`` quando utilizada permite for√ßar uma exce√ß√£o espec√≠fica;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-10-c761920b81b0>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mraise\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "raise KeyboardInterrupt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- Teste o c√≥digo abaixo para digitando quando solicitado ``-1`` e ``Brazil``:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Digite um valor inteiro positivo: -1\n",
      "Erro: o n√∫mero digitado n√£o √© positivo!\n"
     ]
    }
   ],
   "source": [
    "def ler_inteiro_positivo():\n",
    "    a = input(\"Digite um valor inteiro positivo: \")\n",
    "    \n",
    "    if int(a) <= 0:\n",
    "        raise ValueError(\"o n√∫mero digitado n√£o √© positivo!\")\n",
    "\n",
    "try: \n",
    "    ler_inteiro_positivo()\n",
    "except ValueError as e:\n",
    "    print(\"Mensagem de Erro:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Erros definidos pelo usu√°rio\n",
    "\n",
    "- Podemos criar erros espec√≠ficos para nossa aplica√ß√£o.\n",
    "- __Exemplo__: leia um n√∫mero e lance um erro sempre que o valor digitado pelo usu√°rio seja menor que o limite inferior definido ou maior que limite superior definido."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Digite um n√∫mero: 11111111111\n",
      "O valor digitado est√° acima do limite superior\n"
     ]
    }
   ],
   "source": [
    "limiteInferior = 50\n",
    "limiteSuperior = 1000\n",
    "\n",
    "## a classe Exception √© denominada a classe-base para todas as outras\n",
    "## classes de exce√ß√µes que venham a ser criadas.\n",
    "\n",
    "## Portanto, as demais classes definidas pelo usu√°rio devem herdar seus\n",
    "## atributos\n",
    "\n",
    "class ErroIntervalo(Exception):\n",
    "    \"\"\"Valor fora do intervalo.\"\"\"\n",
    "    pass\n",
    "\n",
    "class ErroAbaixoDoLimite(ErroIntervalo):\n",
    "    \"\"\"Valor menor que o limite inferior.\"\"\"\n",
    "    pass\n",
    "\n",
    "\n",
    "class ErroAcimaDoLimite(ErroIntervalo):\n",
    "    \"\"\"Valor maior que o limite superior.\"\"\"\n",
    "    pass\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        numero = int(input(\"Digite um n√∫mero: \"))\n",
    "        if numero < limiteInferior:\n",
    "            raise ErroAbaixoDoLimite\n",
    "    \n",
    "        elif numero > limiteSuperior:\n",
    "            raise ErroAcimaDoLimite\n",
    "    \n",
    "        break\n",
    "\n",
    "    except ErroAbaixoDoLimite:\n",
    "        print(\"O valor digitado est√° abaixo do limite inferior!\")\n",
    "    \n",
    "    except ErroAcimaDoLimite:\n",
    "        print(\"O valor digitado est√° acima do limite superior\")\n",
    "\n",
    "print(\"O valor est√° dentro do intervalo.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- __Boa pr√°tica__: quando definimos nossas pr√≥prias classes de erros, √© aconselh√°vel criar um m√≥dulo separadamente para elas, por exemplo: ``excecoes.py`` ou ``erros.py``.\n",
    "- Estas classes podem ser incrementadas utilizando os conceitos de programa√ß√£o orientada a objetos."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Conclus√£o\n",
    "\n",
    "- Erros sint√°ticos impedem a compila√ß√£o e consequentemente a execu√ß√£o do programa pelo interpretador.\n",
    "- No entanto, exce√ß√µes n√£o impedem a compila√ß√£o e execu√ß√£o do programa, mas no momento que a linha com a exce√ß√£o √© executada teremos problemas.\n",
    "- A estrutura ``try``/``except``/``finally`` √© utilizada para manipula√ß√£o e tratamento de exce√ß√µes."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exerc√≠cios"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__1 - Qual das mensagens abaixo representa um dos erros mais comuns em Python:__ <br>\n",
    "\n",
    "a. SyntaxError: unexpected EOF while parsing <br>\n",
    "b. SyntaxError: EOL while scanning string literal <br>\n",
    "c. SyntaxError: invalid syntax <br>\n",
    "d. SyntaxError: unexpected indent <br>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__2 - Qual(is) da(s) string(s) abaixo n√£o apresenta(m) erro?__ <br>\n",
    "\n",
    "a = 'first string' <br>\n",
    "b = \"second string = first string\" <br>\n",
    "c = \"can it work, I wonder?' <br>\n",
    "d = 'it's really easy to forget' <br>\n",
    "e = 'we \"quote\" it, because we can, can't we?' <br>\n",
    "f = \"\"\"is this even posssible!?\"\"\" <br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__3 - Corrija o c√≥digo abaixo de forma que a primeira linha imprima o resultado da express√£o matem√°tica e a segunda linha imprima ``biologia molecular``:__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(45 / 9 + 16 * (5 + 8))\n",
    "print(\"biologia\" \"molecular\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__4 - Em qual linha do c√≥digo abaixo o interpretador ir√° interromper a execu√ß√£o?__ <br>\n",
    "\n",
    "print( \"Pobre Rei Lear\" )             # 1 <br>\n",
    "print()                               # 2 <br>\n",
    "print'ficou velho')                   # 3 <br>\n",
    "pint()                                # 4 <br>\n",
    "print( ' antes de ficar s√°bio  )      # 5  <br>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__5 - O que acontece quando o interpretador se depara com uma exce√ß√£o?__ <br>\n",
    "\n",
    "a. O programa pede confirma√ß√£o para o programada antes de continuar a execu√ß√£o. <br>\n",
    "b. O programa √© executado at√© a linha com uma exce√ß√£o e ent√£o retorna o traceback. <br>\n",
    "c. O programa encerra apresentando o traceback antes de ser executado. <br>\n",
    "d. O programa √© executado at√© o final ignorando a linha com exce√ß√£o. <br>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__6 - Uma exce√ß√£o √©...__\n",
    "\n",
    "a. Tipo de erro <br> \n",
    "b. Traceback <br>\n",
    "c. Fun√ß√£o <br>\n",
    "d. Vari√°vel <br>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "__7 - O que tem de errado com o c√≥digo abaixo?__\n",
    "\n",
    "age = \"20\" <br>\n",
    "\n",
    "if age < 18: <br>\n",
    "&emsp;print(\"Voc√™ n√£o pode assistir Breaking Bad!\") <br>\n",
    "else: <br>\n",
    "&emsp;print(\"Voc√™ √© benvindo aqui. Divirta-se!\") <br>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
